Repository mirkovic-doo/client, pull requests merged in 2024-08, with the labels that each got.

#5 Feature 4: Added firebase integration
  .env.example
  README.md
  package-lock.json
  package.json
  src/app.html
  src/env.ts
  src/lib/api/apiUser.ts
  src/lib/assets/favicon.ico
  src/lib/auth/firebase.ts
  src/lib/auth/http.ts
  src/lib/stores/userStore.ts
  src/lib/types/user.ts
  src/swagger-templates/api.ejs
  src/swagger-templates/data-contract-jsdoc.ejs
  src/swagger-templates/data-contracts.ejs
  src/swagger-templates/enum-data-contract.ejs
  src/swagger-templates/http-client.ejs
  src/swagger-templates/interface-data-contract.ejs
  src/swagger-templates/object-field-jsdoc.ejs
  src/swagger-templates/procedure-call.ejs
  src/swagger-templates/route-docs.ejs
  src/swagger-templates/route-name.ejs
  src/swagger-templates/route-type.ejs
  src/swagger-templates/route-types.ejs
  src/swagger-templates/type-data-contract.ejs
  vite.config.ts
Labels: feature

#7 Feature 6: Login and Signup UI
  README.md
  package-lock.json
  package.json
  src/app.css
  src/lib/api/apiUser.ts
  src/lib/auth/firebase.ts
  src/lib/auth/http.ts
  src/lib/components/.gitkeep
  src/lib/components/common/Button.svelte
  src/lib/components/common/Input.svelte
  src/lib/stores/authStore.ts
  src/lib/stores/loadingStore.ts
  src/lib/stores/userStore.ts
  src/lib/types/auth.ts
  src/lib/types/user.ts
  src/lib/utils/constants.ts
  src/lib/utils/formConfigs.ts
  src/lib/validations/auth.ts
  src/lib/validations/common.ts
  src/routes/(protected)/+layout.svelte
  src/routes/(protected)/guest/+layout.svelte
  src/routes/(protected)/guest/dashboard/+page.svelte
  src/routes/(protected)/host/+layout.svelte
  src/routes/(protected)/host/dashboard/+page.svelte
  src/routes/(public)/+layout.svelte
  src/routes/(public)/login/+page.svelte
  src/routes/(public)/signup/+page.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
  tailwind.config.js
Labels: feature

#12 Feature 11: Added SignalR Integration
  package-lock.json
  package.json
  src/env.ts
  src/lib/utils/constants.ts
  src/lib/utils/hub.ts
  src/routes/(protected)/+layout.svelte
Labels: feature, technical

#14 Feature 13: Added photo uploading component
  .env.example
  .github/pull_request_template.md
  README.md
  package-lock.json
  src/lib/auth/firebase.ts
  src/lib/components/common/PhotoUpload.svelte
  src/lib/utils/file.ts
  src/routes/(protected)/host/dashboard/+page.svelte
Labels: feature, technical

#17 Feature 9: Update user profile
  package-lock.json
  package.json
  src/app.css
  src/axios/interceptors.ts
  src/lib/components/common/Navbar.svelte
  src/lib/components/profile/ChangePasswordModal.svelte
  src/lib/mappers/user.ts
  src/lib/stores/userStore.ts
  src/lib/types/auth.ts
  src/lib/types/user.ts
  src/lib/utils/constants.ts
  src/lib/utils/formConfigs.ts
  src/lib/validations/auth.ts
  src/routes/(protected)/+layout.svelte
  src/routes/(protected)/guest/+page.svelte
  src/routes/(protected)/host/+page.svelte
  src/routes/(protected)/host/dashboard/+page.svelte
  src/routes/(protected)/user/profile/+page.svelte
  src/routes/(public)/+layout.svelte
  src/routes/(public)/login/+page.svelte
  src/routes/(public)/signup/+page.svelte
  src/routes/+layout.svelte
  src/routes/+page.svelte
Labels: feature

#21 Feature 18: Search properties
  README.md
  src/env.ts
  src/lib/api/apiAccommodation.ts
  src/lib/auth/http.ts
  src/lib/components/search/SearchBar.svelte
  src/lib/mappers/property.ts
  src/lib/types/property.ts
  src/lib/utils/file.ts
  src/routes/(public)/properties/+page.svelte
Labels: feature

#20 Enhancement 19: Changed color of notification button
  src/lib/components/notifications/Notifications.svelte
Labels: enhancement

#23 Feature 22: Create and update of properties
  .env.example
  src/env.ts
  src/lib/api/apiAccommodation.ts
  src/lib/assets/default-house.png
  src/lib/components/common/Navbar.svelte
  src/lib/components/common/PhotoUpload.svelte
  src/lib/components/common/StoragePhotoDisplayer.svelte
  src/lib/components/property/PropertiesDisplay.svelte
  src/lib/components/search/SearchBar.svelte
  src/lib/mappers/property.ts
  src/lib/types/property.ts
  src/lib/utils/formConfigs.ts
  src/lib/validations/property.ts
  src/routes/(protected)/+layout.svelte
  src/routes/(protected)/guest/+page.svelte
  src/routes/(protected)/host/+page.svelte
  src/routes/(protected)/host/property/+page.svelte
  src/routes/(public)/properties/+page.svelte
  src/routes/+layout.svelte
Labels: feature

#26 Feature 24: Handling availability periods
  src/lib/components/property/PropertiesDisplay.svelte
  src/lib/components/property/PropertyCard.svelte
  src/lib/components/search/SearchBar.svelte
  src/lib/mappers/availabilityPeriod.ts
  src/lib/mappers/property.ts
  src/lib/types/availabilityPeriod.ts
  src/lib/utils/date.ts
  src/routes/(protected)/host/+page.svelte
  src/routes/(protected)/host/availabilityPeriods/+page.svelte
  src/routes/(protected)/host/property/+page.svelte
  src/routes/(public)/properties/+page.svelte
Labels: feature
